cloud:
  aws:
    credentials:
      access-key: AKIAYMZJG32FIQNPWGBJ
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: kh-myawsbucket

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
